name: 游 Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ou a branch que voc칡 est치 usando

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 游뚴 Checkout c칩digo
        uses: actions/checkout@v4

      - name: 游늭 Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: 游 Fazer deploy
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Se os arquivos do site estiverem na raiz do reposit칩rio

      - name: 游니 Publicar no GitHub Pages
        uses: actions/deploy-pages@v2
